version: "3.8"
services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - 3000:3000
    env_file:
      - .env.backend   
  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: http://localhost:3000 
    container_name: frontend-container
    ports:
      - 4173:4173
    env_file:
      - .env.frontend
    depends_on:
      - backend

    